### ISSUE TITLE
No getter/setter for `_frozen`

### ISSUE THREAD

**Issue by chillenzer** [edbennett/glue_analysis#1]
Just read through the code and found that apparently `_frozen` plays a central role in `is_consistent` but can be set without reaching into "private" content of the `CorrelatorEnsemble`. We might want to add getter/setter syntax and/or logic that automatically toggles it as needed.

**Comment by edbennett** [comment]
Yes, this was left in from https://github.com/edbennett/meson_analysis/blob/main/meson_analysis/correlator.py as a stub to potentially expand later.

**Comment by chillenzer** [comment]
Got closed at some point.
