### ISSUE TITLE
Underlying data structure

### ISSUE THREAD

**Issue by chillenzer** [edbennett/glue_analysis#11]
I think we should formalise the underlying data structure(s) in the following respects:

- [x] Think about a good structure. I think, for example, that `columns` should be `Op_Index[1,2], Blocking_Index` and `index` should be `Bin_Index, Time`. Or are there advantages from that stacked (or linear) data structure we currently have? How much freedom should the user have in the provided data structure? Currently, there are a lot of implicit assumptions like using `pd.DataFrame` methods and assuming particular column names exist, etc.

- [x] Explicitly define and check this at runtime.

- [x] Formalise/enforce that via type hints / `@property.setter`s.

**Comment by edbennett** [comment]
If we are going to invest mental energy in thinking about this, it would be good if we could harmonise it with edbennett/meson_analysis. (They have already diverged—which is one reason why this is a separate repo—but it would be good to not need to maintain both.) 

(A stretch goal would be harmonisation with edbennett/flow_analysis too.)

My main objective when writing each of the above was to come up with a data structure that a) was very easy to write a reader for, and under that constraint, b) that it was then easy to transform into the data structure I actually wanted (mostly pyerrors objects). I don't necessarily think that a Pandas dataframe is the best choice for these or any other data, but `pd.read_csv` was right there and I reached for it.

Might be worth a discussion in more detail about this. (I don't yet have opinions about `index` vs `columns`; worth settling on whether we want to stick with Pandas first.)

**Comment by chillenzer** [comment]
Okay. Let's solve this iteratively (in the sense of firefighting-ly): My current issue is that I've introduced `Blocking_index` separate from `Op_index`. One could argue that blocking level is part of the operator definition and make `Op_index`, e.g., a tuple of `(<current Op_index>, <current Blocking_index>)`. Or one could generalise the total length check.
