### ISSUE TITLE
Initial values are inconsistent with actual later types

### ISSUE THREAD

**Issue by chillenzer** [edbennett/glue_analysis#2]
The initial values set in `__init__` are inconsistent with the later usage, i.e., later usage assumes to have `pd.DataFrame`s but they are set as lists and dicts.

**Comment by edbennett** [comment]
Good spot—this code was patterned on https://github.com/edbennett/corr_analysis for which those were the right types.

**Comment by chillenzer** [comment]
We don't have initial values anymore. If that's better is a different question.
