### ISSUE TITLE
Does pre-commit.ci run twice?

### ISSUE THREAD

**Issue by chillenzer** [edbennett/glue_analysis#22]
Just thought that the checks on my PRs look slightly weird. There is the `main.yaml` workflow in `.github/workflows` running first and then there is a second step where it directly runs `pre-commit.ci`? We should look into this.

**Comment by edbennett** [comment]
I've been getting pre-commit.ci notifications for other repositories that I haven't added an Action to, so I suspect that you don't need to have both.

**Comment by edbennett** [comment]
OK, db0aff6 should fix this.
