### ISSUE TITLE
Vacuum subtraction normalisation

### ISSUE THREAD

**Issue by edbennett** [edbennett/glue_analysis#28]
Normalisation is currently incorrect. At least for `read_fortran`, the vevs should be divided by `NT * bin_size` (or potentially more easy to calculate: `NT * num_configs / num_bins`), where `NT` refers to the _lattice temporal extent_, not the number of time slices in the correlator (see #27).

As discussed, we probably want to move the responsibility for normalisation from the `CorrelatorEnsemble` to the `reader`, as different types of input will likely have different conventions/summations already applied.

**Comment by chillenzer** [comment]
I'm not sure if we ever actually moved the functionality into `read_binary`. That file wasn't touched in #35. We should totally have another close look at this.

**Comment by chillenzer** [comment]
Oops... #38 tracks this already.
