### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by chillenzer** [edbennett/glue_analysis#3]
Any good reason for not using strict `mypy` mode?

**Comment by edbennett** [comment]
I'm somewhat dubious of adding type annotations before having some way to check their correctness (similar to having comments that can desync from the code); once we have a test suite that we can run `mypy` on then this would seem to make sense.

**Comment by chillenzer** [comment]
On that note: Wanna try [`ruff`](https://astral.sh/ruff) for that? I have read some good things about it recently but never tried it.

**Comment by chillenzer** [comment]
PS: Actually not sure, if it supports type checking by now but for the rest I mean...

**Comment by edbennett** [comment]
Sure, why not
