### ISSUE TITLE
Maybe adopt pre-commit.ci

### ISSUE THREAD

**Issue by chillenzer** [edbennett/glue_analysis#5]
Have just found this. I've already set up a decent `.pre-commit-config.yaml`. [This](https://github.com/marketplace/pre-commit-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW42MTI2#plan-6126) sounds like an efficient way to handle the linting. Any experience with that?

**Comment by edbennett** [comment]
I've seen it around but haven't got around to trying it yet; no objections to doing so.

**Comment by chillenzer** [comment]
This might have a pending action on you to actually install the GH app (or whatever that's called). If you've done so, please close.

**Comment by edbennett** [comment]
Done!
