### ISSUE TITLE
Make consistency check a decorator

### ISSUE THREAD

**Issue by chillenzer** [edbennett/glue_analysis#6]
Probably a prototypical example of bikeshedding but here it comes:

There is already duplicated code in `CorrelatorEnsemble`:
```python3
if not self.is_consistent:
    raise ValueError("Data are inconsistent.")
```
This is like the perfect use case for a decorator:
```python3
def only_on_consistent_data(self, func):
    def func_with_check(*args, **kwargs):
        if not self.is_consistent:
           raise ValueError("Data are inconsistent.")
       return func(*args, **kwargs)
    return func_with_check

@self.only_on_consistent_data
def get_numpy(...):
    ...
```
Would practically make the trivial `get_...` functions oneliners which is what you'd expect them to be.

**Comment by edbennett** [comment]
Bikeshedding perhaps, but reduced duplication is good; I wouldn't have thought of applying a decorator like that, but I like the idea.

**Comment by chillenzer** [comment]
Yeah, it is one of the prototypical examples of [aspect-oriented design](https://en.wikipedia.org/wiki/Aspect-oriented_programming) which I already mentioned in one of our AIMLAC courses and of which I literally always forget the name and have to do `wikipedia.org > "Data-driven design" > scan sidebar for a related name > face-palming myself for having forgotten it`.
